# Generated by Django 6.0 on 2026-02-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100, unique=True)),
                ('available_beds', models.IntegerField()),
                ('medicines', models.TextField()),
                ('sos_active', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmergencyRequest',
        ),
        migrations.DeleteModel(
            name='HospitalAvailability',
        ),
    ]
