# Generated by Django 6.0 on 2026-02-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_tracker', '0002_hospitalstatus_delete_emergencyrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstatus',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalstatus',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
