# Generated by Django 6.0 on 2026-02-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_tracker', '0003_hospitalstatus_latitude_hospitalstatus_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstatus',
            name='sos_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstatus',
            name='sos_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstatus',
            name='sos_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
