# Generated by Django 6.0 on 2026-02-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_tracker', '0004_hospitalstatus_sos_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalstatus',
            name='medicines',
        ),
        migrations.AddField(
            model_name='hospitalstatus',
            name='dexamethasone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalstatus',
            name='icu_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalstatus',
            name='oxygen_cylinders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalstatus',
            name='remdesivir',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalstatus',
            name='ventilators',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitalstatus',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalstatus',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
