# Generated by Django 6.0 on 2026-02-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_tracker', '0005_remove_hospitalstatus_medicines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstatus',
            name='sos_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
