# Generated by Django 6.0 on 2026-02-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_tracker', '0006_hospitalstatus_sos_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstatus',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstatus',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
