# Generated by Django 6.0 on 2026-01-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='Hospital A', max_length=100)),
                ('general_beds', models.PositiveIntegerField(default=0)),
                ('icu_beds', models.PositiveIntegerField(default=0)),
                ('medicine_oxygen', models.BooleanField(default=True)),
                ('medicine_insulin', models.BooleanField(default=True)),
                ('medicine_antibiotics', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
