# Generated by Django 6.0 on 2026-02-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_a', '0002_bedmedicinestatus_delete_hospitalastatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BED', 'Bed'), ('MEDICINE', 'Medicine'), ('EQUIPMENT', 'Equipment')], max_length=20)),
                ('available_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='BedMedicineStatus',
        ),
    ]
